### ISSUE TITLE
Build a Kaleido Eink board with touch and FL support

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/epdiy-hardware-versions#1]
Building a v7 clone that will be tracked in this issue. 
The board still needs to go through many layers and peer reviews before version 1.0 can be sent from fabrication.

I will also blog about the project since JLCPCB, my service provider, is interested to see how is my design process and their engineers where very helpful so far with the epdiy PCB production line. This so far is a very raw take, I just extended v7, and added the connectors in the right positions.

Some facts that we need to take in account in this first revision:

1. **Touch 8 pin FPC and Front-light (FL) 6 pin connector** need to be double checked since at this moment I still do not have the display in my hand. Maybe @bitbank2 can help there to check if the number 1 coincides with the 1 in the display connector (I do not want to send this to fabrication without double-checking this)
2. Focus in this 1.0 is to get display and touch working if possible without any extra fixes. If there must be a wire flying over is not a problem, that is why is Rev. 1.0
3. FL connections are wired, but there is not a 17 V (voltage in page 14 of datasheet) booster circuit in this revision, Cathodes have been connected to GND. Theoretically we can try the FL connecting the +15 Volts that feed the pixels to preview how is going to be. 
4. I quite dislike how is the FL 6 pin connector in this version of Kaleido. It's super close to the display connector when you bend it, making quite impossible to place in the PCB due to yard requirements of the 34 pin connector. 

But that should be by no means the FL power supply. A proper independent boost circuit should be prepared with a Load switch or similar that completely cuts the input power (Since otherwise it will leak and consume when FL is powered OFF)
If the first iteration works, in Rev 1.1 we could add the boost-circuit, plus a P-Channel mosfet that will let GND pass, and can be controlled by a PWM GPIO from the S3 (So we can regulate screen brightness, with this 2 channels)

Marcus on your end can you confirm what is the difference between this 2 LED circuits?
It's one white LED and the other more Warm?

PREVIEWS
![F.cu](https://github.com/martinberlin/epdiy-hardware-versions/assets/2692928/852e48ce-9932-467c-a733-87245a2ae9c0)
Back cooper:
![Kaleido-Bcu](https://github.com/martinberlin/epdiy-hardware-versions/assets/2692928/2a81672f-3787-481e-b401-377e685c8170)

Touch (Quite sure got the pins inverted, 8 should be 1)
![touch_inverted](https://github.com/martinberlin/epdiy-hardware-versions/assets/2692928/80c5643e-97f1-4f28-86da-d341a2bf46d1)
Needs correction

**Comment by martinberlin** [comment]
Added in **1/add-fl-pwm** branch a proposed circuit that I know to work (Only BOOST circuit) using [MT3608](https://www.olimex.com/Products/Breadboarding/BB-PWR-3608/resources/MT3608.pdf)

![17V-Boost-circuit](https://github.com/martinberlin/epdiy-hardware-versions/assets/2692928/e8a1f121-80e6-41de-8612-fdbfef9fd79b)

Then there are 3 control IOs:
- GPIO10: EN_FL_POWER on high it will enable the boost chip, generating stable 17 V after 10 ms.
- GPIO11 & 12: PWM channels so it connects GND via a NPN Transistor to each of the LED circuits.

**Comment by mataide** [comment]
Marcus on your end can you confirm what is the difference between these 2 LED circuits?

@martinberlin Yes, one circuit is for white LED and the other is Warm.

**Comment by martinberlin** [comment]
Thanks @mataide 
If possible please submit a review from your team by Thursday 1 Feb 14:00 so I have time to route the FL boost circuit.
Otherwise is no problem but it will be then sent to fabrication 14 to 15 February as next possible date.

UPDATE: I also need confirmation about the **Front Light Pin 1** location and maybe better a physical test and mark where is + and - pins. Technical drawing of Eink is really bad
![FL_pins rotated](https://github.com/martinberlin/epdiy-hardware-versions/assets/2692928/0b0767bb-cbf1-4f3b-b606-acf44f9bf67f)
Looking at that I'm not sure at all where is one. One of the two images is wrong because with connection pins down the 1 - 6 should be inverted compared with the pins pointing down.

**Comment by Jvinicius06** [comment]
I believe the position of the FP connector is not in a good position for connection because, as you can see in the display drawing, the connector is next to the touch connector.

![image](https://github.com/martinberlin/epdiy-hardware-versions/assets/30390323/d807d5da-d512-464c-8170-d47c030ff3a0)

**Comment by martinberlin** [comment]
@Jvinicius06 the thing is that the display I've has a [different setup](https://mastodon.social/@fasani/111823599852523245) for the FL cable. That's why it's on that position in the PCB. 
If it works then on a next revision I will add also a second connector to support both models

**Comment by mataide** [comment]
@martinberlin You should consider that you are going to receive the model **EC060KH5**, the old one is not available anymore.

**Comment by mataide** [comment]
Also, don't need to create support for the old model **EC060KH3**.

**Comment by Jvinicius06** [comment]
In this case, only the FP connector is in different positions. Isn't it better to put 2 connectors in parallel?

**Comment by martinberlin** [comment]
> In this case, only the FP connector is in different positions. Isn't it better to put 2 connectors in parallel?

Not really in this case since I'm creating a PCB for @mataide which uses the EC060KH5 model.
Now this PCB comes from **epdiy** project and it will be open source. So if anyone wants to modify it can do it considering the License that specifies that versions from this project should be also open source

**Comment by martinberlin** [comment]
@mataide routed the 17 V booster and PWM circuit. KiCad files updated in the branch **1/add-fl-pwm**
![Kaleido-preview-rel1](https://github.com/martinberlin/epdiy-hardware-versions/assets/2692928/053adb19-5b69-4bc9-9a09-4aa8f86fba8d)

**Comment by martinberlin** [comment]
Sent to fabrication yesterday.  Here the JLCPCB corrected part placement (Always one or two parts are rotated and adjusted by their engineering team before entering the Pick and Place data)
![Kaleido-Preview](https://github.com/martinberlin/epdiy-hardware-versions/assets/2692928/38a36032-aad0-434a-aad2-5e438557e2b5)
